<?php

/**
 * @file
 * Contains hook implementations for the Action Link Entity Links module.
 */

use Drupal\Core\Render\Element;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_links_alter().
 */
function action_link_entity_links_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  // TODO - view modes need to be a setting
  $view_mode = $context['view_mode'];

  $user = \Drupal::currentUser();
  // $action_link_entities = \Drupal::service('entity_type.manager')->getStorage('action_link')->loadMultiple();
  // $action_link_entity = \Drupal::service('entity_type.manager')->getStorage('action_link')->load('fuck_bool');
  $action_link_entity = \Drupal::service('entity_type.manager')->getStorage('action_link')->load('has_date');

  $state_action_plugin = $action_link_entity->getStateActionPlugin();
  $action_links = $state_action_plugin->buildLinkArray(
    $action_link_entity,
    $user,
    [
      'entity' => $entity->id(),
    ],
  );

  $action_link_links = [];
  foreach (Element::children($action_links) as $direction) {
    $action_link_links['action_link' . ':' . $action_link_entity->id() . ':' . $direction] = [
      'title' => $action_links[$direction]['#link']['#title'],
      'url' => $action_links[$direction]['#link']['#url'],
      // ARGH we can't set $li_attributes FUCK FUCK
      // need to copy $action_links['dec']['#link']['#attributes']
      // AND stash $action_links['dec']['#attributes']
      // for our PP func to move to the LI.
      // WTF these end up in fucking TEXT attrbutes like we're a fucking SPAN
      'attributes' => $action_links[$direction]['#link']['#attributes'],
    ];

    // We can't set attributes on the LI element at this point, so stash them in
    // a fake key in the link attributes for
    // action_link_entity_links_preprocess_links() to retrieve.
    $action_link_links['action_link' . ':' . $action_link_entity->id() . ':' . $direction]['attributes']['li_class'] = $action_links[$direction]['#attributes']['class'];
  }

  $links['action_link'] = [
    '#theme' => 'links__node__action_link',
    '#links' => $action_link_links,
  ];

  // $links['dummy'] = [
  //   '#theme' => 'links__node__statistics',
  //   '#links' => [
  //     'foo' => [
  //       'title' => 'OH YEAH THIS IS A LINK',
  //     ],
  //   ],
  //   '#attributes' => ['class' => ['links', 'inline']],
  // ];
}

/**
 * Implements hook_preprocess_HOOK() for links.
 */
function action_link_entity_links_preprocess_links(&$variables) {
  // Add LI classes here because AAAAARRRRRRRRGH there is no way to set them
  // with #theme links.
  // See https://www.drupal.org/project/drupal/issues/3436073.
  foreach ($variables['links'] as $key => &$link) {
    if (!str_starts_with($key, 'action_link:')) {
      continue;
    }

    $link['attributes']['class'] = $link['text_attributes']['li_class'];

    // Unset the stash.
    // @todo Doesn't work WTF.
    unset($link['text_attributes']['li_class']);
  }
}
