'action_link.action_link.*':
  type: config_entity
  label: 'Action Link'
  mapping:
    id:
      type: text
      label: 'Machine name'
    label:
      type: label
      label: Name
    plugin_id:
      type: text
      label: 'Plugin ID'
    plugin_config:
      type: ignore
      label: 'Plugin configuration'
