action_link.action_link.*:
  type: config_entity
  label: 'Action Link'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: Name
    plugin_id:
      type: string
      label: 'Plugin ID'
    plugin_config:
      # @todo expand!
      type: ignore
      label: 'Plugin configuration'
    link_style:
      type: string
      label: 'Link style'
