<?php

/**
 * @file
 * Contains hook implementations for the Action Link Field module.
 */

use Drupal\action_link\Plugin\StateAction\EntityFieldStateActionBase;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_ENTITY_TYPE_insert(): action_link
 */
function action_link_field_action_link_insert(EntityInterface $entity) {
  // If a new action_link has the computed field setting, we clear caches so
  // the derived computed field plugin and the computed field definition are
  // picked up.
  if ($entity->getThirdPartySetting('action_link_field', 'computed_field', FALSE)) {
    \Drupal::service('plugin.manager.computed_field')->clearCachedDefinitions();
    \Drupal::service('entity_field.manager')->clearCachedFieldDefinitions();
    Cache::invalidateTags(['entity_field_info']);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update(): action_link
 */
function action_link_field_action_link_update(EntityInterface $entity) {
  // Clear field definition cache if the setting value has changed (because we
  // need to define or remove a field), or if the setting is true (because the
  // field may need to be updated).
  $computed_field_setting = $entity->getThirdPartySetting('action_link_field', 'computed_field', FALSE);
  $computed_field_setting_old_value = $entity->original->getThirdPartySetting('action_link_field', 'computed_field', FALSE);
  if ($computed_field_setting || ($computed_field_setting != $computed_field_setting_old_value)) {
    \Drupal::service('plugin.manager.computed_field')->clearCachedDefinitions();
    \Drupal::service('entity_field.manager')->clearCachedFieldDefinitions();
    Cache::invalidateTags(['entity_field_info']);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete(): action_link
 */
function action_link_field_action_link_delete(EntityInterface $entity) {
  if ($entity->getThirdPartySetting('action_link_field', 'computed_field', FALSE)) {
    \Drupal::service('plugin.manager.computed_field')->clearCachedDefinitions();
    \Drupal::service('entity_field.manager')->clearCachedFieldDefinitions();
    Cache::invalidateTags(['entity_field_info']);
  }
}
